environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
build: off
install:
  - "%PYTHON%\\python.exe -m pip install pytest"
test_script:
  - "%PYTHON%\\python.exe -m pytest wasabi"
after_test:
  - "%PYTHON%\\python.exe setup.py sdist"
